specVersion: 1.0.0
name: SubQuery Dictionary - ethereum
version: 1.0.0
runner:
  node:
    name: "@subql/node-flare"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: >-
  A SubQuery Dictionary Project that provides increased indexing speed to all
  projects
repository: "https://github.com/subquery/ethereum-dictionary"
schema:
  file: "./schema.graphql"

network:
  endpoint: https://flare-api.flare.network/ext/C/rpc
  chainId: "14"

dataSources:
  - kind: flare/Runtime
    startBlock: 1
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleBlock
          kind: flare/BlockHandler
